---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - .tox

before_install:
  - openssl aes-256-cbc -K $encrypted_0aa4db5f6f62_key -iv $encrypted_0aa4db5f6f62_iv -in molecule/default/clouds.yml.enc -out molecule/default/clouds.yml -d

install:
  - pip install -r test-requirements.txt

env:
  - TOX_ENV=ansible25 MOLECULE_IMAGE="Ubuntu 16.04 (20180628)"
  - TOX_ENV=ansible26 MOLECULE_IMAGE="Ubuntu 16.04 (20180628)"
  - TOX_ENV=ansible25 MOLECULE_IMAGE="Ubuntu 18.04 (20180627)"
  - TOX_ENV=ansible26 MOLECULE_IMAGE="Ubuntu 18.04 (20180627)"

script:
  - tox -e $TOX_ENV

after_failure:
  - tox -e destroy

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
