---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: molecule-ubuntu-template
    image: ubuntu
    image_version: 16.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
